version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: elasticsearch:7.14.2
    environment:
      - "xpack.security.enabled=false"       # Disables xpack security
      - "xpack.monitoring.enabled=false"     # Disables xpack monitoring
      - "xpack.watcher.enabled=false"        # Disables xpack watcher
      - "xpack.ml.enabled=false"             # Disables xpack machine learning
      - "discovery.type=single-node"
    networks:
      - es-net
    volumes:
      - /home/lord/workspace/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  cerebro: 
    image: lmenezes/cerebro:0.8.3
    container_name: cerebro-container
    ports:
      - "9000:9000"
    networks:
      - es-net
    command:
      - -Dhosts.0.host=http://elasticsearch:9200

  kibana:
    container_name: kb-container
    image: kibana:7.14.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  es-net:
    driver: bridge